// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: surface_level

#ifndef _SURFACE_LEVEL_UI_H
#define _SURFACE_LEVEL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"
#include "ui_Screen2.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_surface_level_png);    // assets/surface level.png
LV_IMG_DECLARE(ui_img_bubble_png);    // assets/bubble.png
LV_IMG_DECLARE(ui_img_target_off_png);    // assets/target_off.png
LV_IMG_DECLARE(ui_img_target_on_png);    // assets/target_on.png
LV_IMG_DECLARE(ui_img_makers_png);    // assets/makers.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
