// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: surface_level

#include "ui.h"

// COMPONENT bubble

lv_obj_t * ui_bubble_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_bubble;
    cui_bubble = lv_button_create(comp_parent);
    lv_obj_set_width(cui_bubble, 50);
    lv_obj_set_height(cui_bubble, 50);
    lv_obj_set_align(cui_bubble, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_bubble, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(cui_bubble, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_BUBBLE_NUM);
    children[UI_COMP_BUBBLE_BUBBLE] = cui_bubble;
    lv_obj_add_event_cb(cui_bubble, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_bubble, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_bubble_create_hook(cui_bubble);
    return cui_bubble;
}

