// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: surface_level

#ifndef _UI_COMP_BUBBLE_H
#define _UI_COMP_BUBBLE_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT bubble
#define UI_COMP_BUBBLE_BUBBLE 0
#define _UI_COMP_BUBBLE_NUM 1
lv_obj_t * ui_bubble_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
